version: '3.8'

services:
  patkid_client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: 8574
    environment:
      - TZ=Asia/Seoul # 컨테이너 내부 시간대를 KST로 설정
      - NODE_ENV=production # 프로덕션 환경으로 설정
    image: patkid_client
    ports:
      - '8574:8574'
    networks:
      - app

networks:
  app:
    external: true
    name: app
